### ISSUE TITLE
Doing something about the docs

### ISSUE THREAD

**Issue by mdlkxzmcp** [lambdaacademy/orangeade#14]
I have noticed that most of the function docs contain examples that are just unreadable. Usually this can be fixed by limiting the "size" of arguments passed in the examples, like so:
Instead of `iex(1)> s = Orangeade.Generator.PrintableASCIICharlist.stream(max_word_length: 30)`
Pass in `iex(1)> s = Orangeade.Generator.PrintableASCIICharlist.stream(max_word_length: 5)`

This makes the docs more readible without loosing the feature it is trying to showcase. Tests are the part of the code that should actually have bigger values as that gives a higher chance of catching unusual bugs.

**Comment by sebb7** [comment]
I think that the documentation should show how the function works and the fact that I would like to see up to 30 element charlists does not matter. @Mdlkxzmcp, maybe I do not get the point but please clarify what is the "issue" here.

**Comment by mdlkxzmcp** [comment]
This specific example might have not really reflected the problem, although I see that you did indeed shorten the docs in a way that makes them way less messy to read. The main issue was the overall noise created by unnecessarily big examples, which, as long as the overall description is good, should not be needed to understand the behavior of the function.

Especially this type of docs was what I was referring to:
```Elixir
  iex> a = Orangeade.Generator.Logical.stream()                
      [false | #Function<1.23635164/0 in Caffeine.Stream.map/2>]
  iex> b = Orangeade.Generator.PrintableASCIICharacter.stream()
      [33 | #Function<1.23635164/0 in Caffeine.Stream.map/2>]
  iex> c = Orangeade.Generator.BoundNatural.stream(limit: 13)  
      [1 | #Function<1.23635164/0 in Caffeine.Stream.map/2>]
```

The current implementations are really nice though and I think this issue is fixed. :>
